// data.js — АВТОМАТИЧЕСКИ СГЕНЕРИРОВАННЫЙ файл (см. doc/CORS.md, doc/SYNC.md).
// Содержит копию notes/ и SPARQL/ для запуска по file:// без CORS.
// Пересоздать: кнопка «Экспорт data.js» в интерфейсе или `node tests/build-data.js`.
window.MDLD_DATA = {
  "notes": {
    "note1.md": "[ex] <tag:example.org,2026:>\n[schema] <http://schema.org/>\n\n# Алиса {=ex:alice .schema:Person schema:name}\n\nАлиса — вымышленная персона для тестирования семантической разметки MD-LD.\n\nАдрес Алисы: [Адрес Алисы] {+ex:alice-addr ?schema:address}.\n\nАлиса увлекается [фотографией] {+ex:alice-hobby-photo ?schema:knowsAbout}\nи [шахматами] {+ex:alice-hobby-chess ?schema:knowsAbout}.\n\n## Адрес Алисы {=ex:alice-addr .schema:PostalAddress schema:name}\n\n[ул. Ленина, д. 10] {schema:streetAddress}\n[Москва] {schema:addressLocality}\n[101000] {schema:postalCode}\n[Россия] {schema:addressCountry}\n\n## Фотография {=ex:alice-hobby-photo .schema:Thing schema:name}\n\n## Шахматы {=ex:alice-hobby-chess .schema:Thing schema:name}\n\n# Боб {=ex:bob .schema:Person schema:name}\n\nБоб — второй вымышленный персонаж.\n\nАдрес Боба: [Адрес Боба] {+ex:bob-addr ?schema:address}.\n\nБоб увлекается [велоспортом] {+ex:bob-hobby-bike ?schema:knowsAbout}\nи [программированием] {+ex:bob-hobby-code ?schema:knowsAbout}.\n\n## Адрес Боба {=ex:bob-addr .schema:PostalAddress schema:name}\n\n[ул. Пушкина, д. 25] {schema:streetAddress}\n[Химки] {schema:addressLocality}\n[141400] {schema:postalCode}\n[Россия] {schema:addressCountry}\n\n## Велоспорт {=ex:bob-hobby-bike .schema:Thing schema:name}\n\n## Программирование {=ex:bob-hobby-code .schema:Thing schema:name}\n",
    "note2.md": "[ex] <tag:example.org,2026:>\n[schema] <http://schema.org/>\n\n# Расстояние между Алисой и Бобом {=ex:dist-alice-bob .ex:Distance schema:name}\n\nАлиса и Боб живут друг от друга на расстоянии 11 километров.\n\n[11] {schema:value ^^xsd:integer}\n[km] {schema:unitText}\n\nОт кого: [Алиса] {+ex:alice ?ex:from}.\nК кому: [Боб] {+ex:bob ?ex:to}.\n\n# Example Corp {=ex:org-example .schema:Organization schema:name}\n\n[IT-компания] {schema:description}\n\n# Место работы Алисы {=ex:alice}\n\nАлиса работает в [Example Corp] {+ex:org-example ?schema:worksFor}.\n\n# Место работы Боба {=ex:bob}\n\nБоб работает в [Example Corp] {+ex:org-example ?schema:worksFor}.\n"
  },
  "SPARQL": {
    "01-all-triples.rq": "SELECT ?s ?p ?o\nWHERE {\n  ?s ?p ?o .\n}\nLIMIT 100\n",
    "02-all-notes.rq": "# Все именованные ресурсы и их типы (в заметках нет schema:CreativeWork,\n# поэтому запрос ver2 был пустым — здесь выбираем все сущности с именем).\nPREFIX schema: <http://schema.org/>\n\nSELECT ?entity ?type ?name\nWHERE {\n  ?entity a ?type ;\n          schema:name ?name .\n}\nORDER BY ?type ?name\n",
    "03-notes-by-author.rq": "# Количество сущностей каждого типа (вместо подсчёта заметок по авторам:\n# в заметках нет schema:author).\nSELECT ?type (COUNT(?entity) AS ?count)\nWHERE {\n  ?entity a ?type .\n}\nGROUP BY ?type\nORDER BY DESC(?count)\n",
    "04-persons.rq": "# Все персоны. В ver2 было пусто: префикс schema не был объявлен в заметках,\n# и mdld-parse создавал IRI <schema:Person> вместо <http://schema.org/Person>.\nPREFIX schema: <http://schema.org/>\n\nSELECT ?person ?name ?city\nWHERE {\n  ?person a schema:Person ;\n          schema:name ?name .\n  OPTIONAL { ?person schema:address/schema:addressLocality ?city }\n}\nORDER BY ?name\n",
    "05-hobbies.rq": "# Увлечения персон. В ver2 переменная ?hobbyName не выводилась, а данные были пустыми.\nPREFIX schema: <http://schema.org/>\n\nSELECT ?personName ?hobbyName\nWHERE {\n  ?person a schema:Person ;\n          schema:name ?personName ;\n          schema:knowsAbout ?hobby .\n  ?hobby schema:name ?hobbyName .\n}\nORDER BY ?personName ?hobbyName\n",
    "06-worksfor.rq": "# Место работы персон.\nPREFIX schema: <http://schema.org/>\n\nSELECT ?personName ?orgName\nWHERE {\n  ?person schema:name ?personName ;\n          schema:worksFor ?org .\n  ?org schema:name ?orgName .\n}\nORDER BY ?personName\n",
    "07-distance.rq": "# Расстояние между персонами.\nPREFIX schema: <http://schema.org/>\nPREFIX ex: <tag:example.org,2026:>\n\nSELECT ?fromName ?toName ?value ?unit\nWHERE {\n  ?dist a ex:Distance ;\n        schema:value ?value ;\n        schema:unitText ?unit ;\n        ex:from ?from ;\n        ex:to ?to .\n  ?from schema:name ?fromName .\n  ?to schema:name ?toName .\n}\n"
  }
};
